# Generated by Django 5.0.1 on 2024-10-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid_requesttype', models.CharField(max_length=100)),
                ('cpn', models.CharField(max_length=100)),
                ('mpn', models.CharField(max_length=100)),
                ('mfr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_code', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=100)),
                ('sales_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_comment', models.TextField(blank=True, null=True)),
                ('source_email', models.FileField(upload_to='documents/')),
                ('reference_code', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=50)),
                ('request_id', models.CharField(max_length=100)),
                ('request_status', models.CharField(max_length=50)),
                ('total_parts_count', models.PositiveIntegerField(default=0)),
                ('matched_parts_count', models.PositiveIntegerField(default=0)),
                ('unmatched_parts_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TotalParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid_requesttype', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cpn', models.CharField(max_length=100)),
                ('mpn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnmatchedParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid_requesttype', models.CharField(max_length=100)),
                ('cpn', models.CharField(max_length=100)),
                ('mpn', models.CharField(blank=True, max_length=100, null=True)),
                ('mfr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
